[build]
builder = "nixpacks"
buildCommand = "cd MyInventory/backend && pip3 install -r requirements.txt && python3 manage.py collectstatic --noinput"

[deploy]
startCommand = "cd MyInventory/backend && gunicorn config.wsgi:application"
healthcheckPath = "/admin/"
restartPolicyType = "on_failure"